name: CI/CD for teii Package

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs called "test-package" and "build-and-publish-package"

  test-package:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      # Run all the combinations even if one of them fails
      fail-fast: false

      matrix:
        include:
          - os: ubuntu-22.04
            python-version: "3.11"
            tox-env: py311
          - os: ubuntu-22.04
            python-version: "3.12"
            tox-env: py312
          - os: ubuntu-22.04
            python-version: "3.13"
            tox-env: py313
          - os: ubuntu-24.04
            python-version: "3.11"
            tox-env: py311
          - os: ubuntu-24.04
            python-version: "3.12"
            tox-env: py312
          - os: ubuntu-24.04
            python-version: "3.13"
            tox-env: py313
    defaults:
      run:
        # the location of tox.ini and setup.py
        working-directory: teii-finance.2025-26

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v5

    # Sets up python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    # Installs tox
    - name: Install tox
      run: |
        pip install tox==4.25.0

    # Runs tox
    - name: Run flake8, mypy and pytest with tox
      run: |
        tox -e lint,${{ matrix.tox-env }}

  build-and-publish-package:
    # the package is published only when te workflow is manually launched 
    # this is for avoid publishing a new wheel on every push or pull request
    if: github.event_name == 'workflow_dispatch'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test-package

    defaults:
      run:
        # location of setup.py
        working-directory: teii-finance.2025-26

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v5

    # Sets up python version
    - name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: 3.11

    # Builds the package
    - name: Build package
      run: |
        pip install setuptools wheel
        python setup.py bdist_wheel

    # Publishes the package to TestPypi
    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_TESTPYPI_TOKEN }}
        TWINE_REPOSITORY: testpypi
      run: |
          pip install twine
          python3 -m twine upload dist/*
