[tox]
envlist = lint, py311, py312, py313
toxworkdir = /tmp/.tox

[flake8]
max-line-length = 120

[testenv]
package = wheel
deps =
    -r requirements-dev.txt
commands =
    pytest -rA -v --cov teii --cov-report term-missing tests/finance

[testenv:lint]
package = skip
deps =
    -r requirements-dev.txt
commands =
    flake8 teii
    mypy -v -m teii.finance --ignore-missing-imports    
